export const MOCK_REQUESTS = [
  {
    id: "REQ68001",
    date: "10/03/2569",
    itemsCount: 3,
    branch: "สำนักงานใหญ่",
    status: "pending",
    approver: "รออนุมัติ",
    requester: "นายธีรชัย บุญมาก",
    items: [
      { name: "กระดาษ A4 80 แกรม", quantity: 5, unit: "รีม" },
      { name: "ปากกาเจล สีดำ", quantity: 12, unit: "ด้าม" },
      { name: "แฟ้มเอกสาร", quantity: 4, unit: "แฟ้ม" },
    ],
  },
  {
    id: "REQ68002",
    date: "09/03/2569",
    itemsCount: 2,
    branch: "สาขาพัทลุง",
    status: "approved",
    approver: "ผู้จัดการเขตภาคเหนือ",
    requester: "นางสาวอรทัย ศรีสุข",
    items: [
      { name: "หมึกพิมพ์ Canon 325", quantity: 2, unit: "ตลับ" },
      { name: "กระดาษโฟโต้", quantity: 3, unit: "แพ็ค" },
    ],
  },
  {
    id: "REQ68003",
    date: "08/03/2569",
    itemsCount: 4,
    branch: "สาขาพัทลุง",
    status: "processing",
    approver: "Admin กลาง",
    requester: "นายณัฐวุฒิ ใจกล้า",
    items: [
      { name: "เมาส์ไร้สาย", quantity: 5, unit: "ตัว" },
      { name: "คีย์บอร์ด USB", quantity: 3, unit: "ตัว" },
      { name: "สาย HDMI", quantity: 6, unit: "เส้น" },
      { name: "แผ่นรองเมาส์", quantity: 5, unit: "แผ่น" },
    ],
  },
  {
    id: "REQ68004",
    date: "07/03/2569",
    itemsCount: 1,
    branch: "สาขารัตภูมิ",
    status: "completed",
    approver: "ผู้จัดการสาขา",
    requester: "นางสาวปวีณา ทองดี",
    items: [
      { name: "เครื่องพิมพ์เลเซอร์ HP", quantity: 1, unit: "เครื่อง" },
    ],
  },
  {
    id: "REQ68005",
    date: "06/03/2569",
    itemsCount: 2,
    branch: "สาขาจะนะ",
    status: "rejected",
    approver: "หัวหน้าฝ่ายการเงิน",
    requester: "นายกิตติพงษ์ แซ่ตั้ง",
    items: [
      { name: "ฮาร์ดดิสก์พกพา 2TB", quantity: 2, unit: "ตัว" },
      { name: "แฟลชไดรฟ์ 64GB", quantity: 10, unit: "อัน" },
    ],
  },
  {
    id: "REQ68006",
    date: "05/03/2569",
    itemsCount: 3,
    branch: "สาขาหาดใหญ่",
    status: "approved",
    approver: "ผู้อำนวยการฝ่ายจัดซื้อ",
    requester: "นางสาวสุพัตรา วัฒนะ",
    items: [
      { name: "ลวดเย็บกระดาษ", quantity: 5, unit: "กล่อง" },
      { name: "เครื่องเย็บกระดาษ", quantity: 3, unit: "อัน" },
      { name: "เทปใส", quantity: 8, unit: "ม้วน" },
    ],
  },
  {
    id: "REQ68007",
    date: "04/03/2569",
    itemsCount: 2,
    branch: "สาขาหาดใหญ่",
    status: "processing",
    approver: "Admin กลาง",
    requester: "นายอาทิตย์ ใจดี",
    items: [
      { name: "โน้ตบุ๊กสำนักงาน", quantity: 2, unit: "เครื่อง" },
      { name: "เมาส์ USB", quantity: 2, unit: "ตัว" },
    ],
  },
];